name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl https://www.golfchannel.com/api/v2/events/19965/leaderboard | jq . > leaderboard.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}"
        git push
